### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by samdunne** [joefiorini/vruby#1]
I'm happy to write the formula and help along with other things if you like.

**Comment by joefiorini** [comment]
Before writing a home brew formula I want to make it work on OSX and support other Ruby versions. I think the only change needed for OSX support will be to download the OSX Traveling Ruby package instead of the Linux one. We'll also need a file that maps these URLs per platform & version.

I'll work on that soon and post back here when it's done. Would you mind testing out the OSX support when it's ready?

**Comment by samdunne** [comment]
Sure no problem. Would changing this to be written in Go not help the entire process?

**Comment by joefiorini** [comment]
@samdunne I opened #2 to track basic OS X support and #3 for rewriting in Go. Let's continue these conversations there.

**Comment by joefiorini** [comment]
Fixed in 7cd12ca83da83b27411a1aaff51a5aeee02a4798
